[*] Running ...
Traceback (most recent call last):
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1825, in apply
    result = self._python_apply_general(f, self._selected_obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1886, in _python_apply_general
    values, mutated = self._grouper.apply_groupwise(f, data, self.axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 919, in apply_groupwise
    res = f(group)
          ^^^^^^^^
  File "/home/rjj/reevo/problems/backtest/eval.py", line 21, in <lambda>
    market_data['factor'] = market_data.groupby('stock_code').apply(lambda x: heuristics(x)).reset_index(level=0, drop=True)
                                                                              ^^^^^^^^^^^^^
  File "/home/rjj/reevo/problems/backtest/gpt.py", line 7, in heuristics_v2
    df['TR'] = df[['TR', (df['close'].shift(1) - df['high']).abs(), (df['close'].shift(1) - df['low']).abs()]].max(axis=1)
               ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/frame.py", line 4113, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6207, in _get_indexer_strict
    indexer = self.get_indexer_for(keyarr)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6194, in get_indexer_for
    return self.get_indexer(target)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3960, in get_indexer
    return self._get_indexer(target, method, limit, tolerance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3987, in _get_indexer
    indexer = self._engine.get_indexer(tgt_values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 351, in pandas._libs.index.IndexEngine.get_indexer
  File "pandas/_libs/hashtable_class_helper.pxi", line 7139, in pandas._libs.hashtable.PyObjectHashTable.lookup
TypeError: unhashable type: 'Series'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rjj/reevo/problems/backtest/eval.py", line 60, in <module>
    mean_ic = solve(market_data)
              ^^^^^^^^^^^^^^^^^^
  File "/home/rjj/reevo/problems/backtest/eval.py", line 21, in solve
    market_data['factor'] = market_data.groupby('stock_code').apply(lambda x: heuristics(x)).reset_index(level=0, drop=True)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1847, in apply
    return self._python_apply_general(f, self._obj_with_exclusions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1886, in _python_apply_general
    values, mutated = self._grouper.apply_groupwise(f, data, self.axis)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 919, in apply_groupwise
    res = f(group)
          ^^^^^^^^
  File "/home/rjj/reevo/problems/backtest/eval.py", line 21, in <lambda>
    market_data['factor'] = market_data.groupby('stock_code').apply(lambda x: heuristics(x)).reset_index(level=0, drop=True)
                                                                              ^^^^^^^^^^^^^
  File "/home/rjj/reevo/problems/backtest/gpt.py", line 7, in heuristics_v2
    df['TR'] = df[['TR', (df['close'].shift(1) - df['high']).abs(), (df['close'].shift(1) - df['low']).abs()]].max(axis=1)
               ~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/frame.py", line 4113, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6207, in _get_indexer_strict
    indexer = self.get_indexer_for(keyarr)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6194, in get_indexer_for
    return self.get_indexer(target)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3960, in get_indexer
    return self._get_indexer(target, method, limit, tolerance)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rjj/miniconda3/envs/ReEvo/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3987, in _get_indexer
    indexer = self._engine.get_indexer(tgt_values)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 351, in pandas._libs.index.IndexEngine.get_indexer
  File "pandas/_libs/hashtable_class_helper.pxi", line 7139, in pandas._libs.hashtable.PyObjectHashTable.lookup
TypeError: unhashable type: 'Series'
